robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: motortom2m
    pid: {p: 25000.0, i: 0.1, d: 350.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 20000.0, i: 0.1, d: 350.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 15000.0, i: 0.1, d: 350.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint6
    pid: {p: 10000.0, i: 0.1, d: 350.0}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: end
    pid: {p: 5000, i: 0.1, d: 350.0}


